apiVersion: v1
kind: Service
metadata:
  name: myreds
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: redmine
---
apiVersion: v1
kind: Service
metadata:
  name: myreds-dashboard
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 81
    targetPort: 80
  selector:
    app: dashboard
