apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redmine
spec:
  serviceName: redmine-cluster
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:5.0.6-alpine
        ports:
        - containerPort: 3000
        env:
        - name: REDMINE_DB_POSTGRES
          value: postgres-service
        - name: REDMINE_DB_DATABASE
          value: redmine
        - name: REDMINE_DB_USERNAME
          value: pguser
        - name: REDMINE_DB_PASSWORD
          value: pgpass
        volumeMounts:
        - name: redmine-files
          mountPath: /usr/src/redmine/files
  volumeClaimTemplates:
    - metadata:
        name: redmine-files
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests: 
            storage: 10Mi
