apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myprojects
  labels:
    app: redmine
spec:
  serviceName: redmine-cluster
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: myprojects
        image: redmine:5.0.6-alpine
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: redmine-files
          mountPath: /usr/src/redmine/files
  volumeClaimTemplates:
    - metadata:
        name: redmine-files
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests: 
            storage: 10Mi
