apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-files
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  hostPath:
    path: /tmp/hostpath-provisioner/default/redmine-files/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
  volumeName: redmine-files
