apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprojects
  labels:
    app: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: myprojects
        image: redmine:5.0.6-alpine
        ports:
        - containerPort: 3000
