apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redmine
spec:
  serviceName: redmine-cluster
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:5.0.6-alpine
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: redmine-files
          mountPath: /usr/src/redmine/files
  volumeClaimTemplates:
    - metadata:
        name: redmine-files
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests: 
            storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-service
  labels:
    app: redmine
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    nodePort: 30000
    protocol: TCP
  selector:
    app: redmine
